sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t konszogr/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true konszogr/react-test npm test

after_success:
  - docker build -t konszogr/multi-client ./client
  - docker build -t konszogr/multi-nginx ./nginx
  - docker build -t konszogr/multi-server ./server
  - docker build -t konszogr/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push konszogr/multi-client
  - docker push konszogr/multi-nginx
  - docker push konszogr/multi-server
  - docker push konszogr/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "Multi-docker"
  env: "Multi-docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-954640356888"
  bucket_path: "docker-multi"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY